### ISSUE TITLE
how to use it ?

### ISSUE THREAD

**Issue by A-A-Haggag** [way2-technology/visual-studio-project-renamer#2]
how can i use it ?

**Comment by thcerutti** [comment]
Hi Ahmed, this project was created a loooong time ago (at that time we needed this kind of solution), but fortunately nowadays we have native tools for renaming projects, much easier. We keep this repo as a... code museum, let's say :D

**Comment by A-A-Haggag** [comment]
thanks a lot, could you tell me a way to do it in an easy way ?

**Comment by thcerutti** [comment]
you can rename the .csproj file and the root folder, and then change the path to the new .csproj file in the  .vscode folder (if you use vs code) and that's it. Or if you use Visual Studio, try something this: https://medium.com/@rodlauroromarate/how-to-rename-an-asp-net-core-project-ad6d93cc3df4
